services:
  postgres:
    image: postgres:15
    container_name: schema-builder-db
    restart: always
    environment:
      POSTGRES_USER: schema_user
      POSTGRES_PASSWORD: schema_pass
      POSTGRES_DB: schema_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
